WITH CTE AS (
SELECT
TO_TIMESTAMP(STARTED_AT),
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)),
case 
    when DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,
--MACRO
 {{station('STARTED_AT')}} as station_of_year

from
{{ ref('stg_bike') }}
)

SELECT * FROM CTE