WITH BIKE AS (
SELECT
RIDE_ID ,
REPLACE(STARTED_AT,'"','')  AS STARTED_AT,
REPLACE(ENDED_AT,'"','')  AS ENDED_AT,
START_STATION_NAME ,
START_SATION_ID ,
END_STATION_NAME ,
END_STATION_ID ,
START_LAT ,
START_LON ,
END_LAT ,
END_LON ,
MENBER_CSUAL 

FROM {{ source('demo', 'bike_table') }}
where RIDE_ID != 'bikeid'
)

SELECT * FROM BIKE