WITH TRIPS  AS (
SELECT
RIDE_ID,
--RIDEABLE_TYPE,
TO_TIMESTAMP(STARTED_AT) AS TRIP_DATE,
START_SATION_ID,
END_STATION_ID,
MENBER_CSUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT))  AS TRIP_DURATION    

FROM {{ ref('stg_bike') }}
)
SELECT * 
FROM TRIPS